workspace:
  base: /root
  path: /wxapi

pipeline:
  docker_auth:
    image: plugins/docker
    repo: coderxu/wxapi_auth
    target: production
    secrets: [docker_username, docker_password]
    dockerfile: ./auth/Dockerfile

  scp_compose_yml:
    group: build
    image: appleboy/drone-scp
    host: 45.76.96.204
    secrets: [ssh_username, ssh_password]
    port: 22
    target: /root/wxapi/
    source: ./auth/docker-compose.yml
    strip_components: 1

  ssh_compose_start:
    image: appleboy/drone-ssh
    host: 45.76.96.204
    secrets: [ssh_username, ssh_password]
    port: 22
    script:
      - sudo docker pull coderxu/wxapi_auth
      - sudo docker network list -f name=internal | wc -l | awk '$0==1{cmd="sudo docker network create internal";system(cmd)}'
      - sudo docker-compose -f ./auth/docker-compose.yml down
      - sudo docker-compose -f ./auth/docker-compose.yml up -d

  wechat_notification:
    image: lizheming/drone-wechat
    secrets: [wechat_corpid, wechat_corp_secret, wechat_agent_id, wechat_to_tag]
    msg_url: ${DRONE_BUILD_LINK}
    safe: 0
    btn_txt: ok
    title: ${DRONE_REPO_NAME}
    message: >
      {%if success %}
        构建版本 {{build.number}} 成功. 开始测试业务流程吧.
      {% else %}
        构建版本 {{build.number}} 失败. 请查找一下问题所在.
      {% endif %}
    when:
      status: [success, failure]
