workspace:
  base: /root
  path: /wxapi

pipeline:
  backend:
    image: golang
    commands:
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./auth/app ./auth
  docker:
    image: plugins/docker
    repo: coderxu/wxapi_auth
    target: production
    username: coderxu
    password: wangxu226
    dockerfile: ./auth/Dockerfile



