workspace:
  base: /root
  path: /wxapi

pipeline:
  backend:
    image: golang
    ports:
      - 8021:8021
    commands:
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app ./auth
      - ./app
      


