workspace:
  base: /root
  path: /wxapi

pipeline:
  backend:
    image: golang
    commands:
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./auth/app ./auth
  docker:
    image: plugins/docker
    repo: coderxu/wxapi_auth
    target: production
    username: coderxu
    password: wangxu226
    dockerfile: ./auth/Dockerfile
  scp:
    image: appleboy/drone-scp
    host: 45.76.96.204
    username: root
    password: k4W)YTgK1w,(mVZC
    port: 22
    target: /root/wxapi/
    source: ./auth/docker-compose.yml
    strip_components: 1

  ssh:
    image: appleboy/drone-ssh
    host: 45.76.96.204
    username: root
    password: k4W)YTgK1w,(mVZC
    port: 22
    script: 
      - sudo docker pull coderxu/wxapi_auth
      - sudo docker network list -f name=internal | wc -l | awk '$0==1{cmd="sudo docker network create internal";system(cmd)}'
      - sudo docker-compose -f /root/wxapi/auth/docker-compose.yml down
      - sudo docker-compose -f /root/wxapi/auth/docker-compose.yml up -d
  wechat:
    image: lizheming/drone-wechat
    corpid: ww4854a2c3aaec98f9
    corp_secret: -mPkllfoA6xjpsrHpvr3_bxp3yV9HYkiz2l5SxvkRaM 
    agent_id: 1000002
    to_tag: 1
    msg_url: ${DRONE_BUILD_LINK}
    safe: 0
    btn_txt: more
    title: ${DRONE_REPO_NAME}
    message: >
      {%if success %}
        build {{build.number}} succeeded. Good job.
      {% else %}
        build {{build.number}} failed. Fix me please.
      {% endif %}
    when:
      status: [success,failure]

