workspace:
  base: /root
  path: /wxapi

pipeline:
  backend:
    image: golang
    commands:
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./auth/app ./auth
  docker:
    image: plugins/docker
    repo: coderxu/wxapi_auth
    target: production
    username: coderxu
    password: wangxu226
    dockerfile: ./auth/Dockerfile
  ssh:
    image: appleboy/drone-ssh
    host: 45.76.96.204
    username: root
    password: k4W)YTgK1w,(mVZC
    port: 22
    script:
      - sudo docker pull coderxu/wxapi_auth
      - sudo docker rm -f wxapi_auth
      - sudo docker run --name wxapi_auth -p 8021:8021 -d coderxu/wxapi_auth
  wechat:
    image: lizheming/drone-wechat
    corpid: ww4854a2c3aaec98f9
    corp_secret: -mPkllfoA6xjpsrHpvr3_bxp3yV9HYkiz2l5SxvkRaM 
    agent_id: 1000002
    to_user: WangXu
    safe: 1
    btn_txt: more_text
    title: ${DRONE_REPO_NAME}
    message: >
      {%if success %}
        build {{build.number}} succeeded. Good job.
      {% else %}
        build {{build.number}} failed. Fix me please.
      {% endif %}
    when:
      status: [success,failure]

