version: "2"

services:
  wxapi_micro_auth:
    image: registry.cn-shanghai.aliyuncs.com/xugopher/wx_micro_auth
    networks:
      - internal
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY_ADDRESS: consul:8500
      MysqlURL: mariadb:3306
      WXAppSecrect: ${WXAppSecrect}
  wxapi_api_auth:
    image: registry.cn-shanghai.aliyuncs.com/xugopher/wx_api_handler
    networks:
      - internal
    depends_on:
      - wxapi_micro_auth
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: consul:8500
      WXAppSecrect: ${WXAppSecrect}

networks:
  internal:
    external: true
