version: "2"

services:
  micro:
    image: microhq/micro
    command: list services
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: consul:8500
networks:
  internal:
    external: true
