version: "2"

services:
  wxapi_auth:
    image: coderxu/wxapi_auth
    networks:
      - internal
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY_ADDRESS: consul:8500
      MysqlURL: mariadb:3306
networks:
  internal:
    external: true
