version: "2"

services:
  wxapi_auth:
    image: coderxu/wxapi_auth
    networks:
      - internal
    ports:
      - 50051:50051
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_SERVER_ADDRESS: ":50051"

networks:
  internal:
    external: true
