version: "2"

services:
  wxapi_auth:
    image: coderxu/wxapi_auth
    networks:
      - internal
    environment:
      MICRO_REGISTRY: consul
      MICRO_REGISTRY_ADDRESS: http://consul:8500

networks:
  internal:
    external: true
